package ghp.vgcproject.main.gfx;

import java.util.HashMap;

public class Daten {

	public HashMap<String,String> TextWechselZuPassenderKategorie = new HashMap<String,String>();
	
	public Daten()//HashMap um easy die JTextAreaTexte zu wechseln
	{
		TextWechselZuPassenderKategorie.put("Versuch", "Nehmen wir als Beispiel die zwei Pokémon Arbok(Gift) und Tukanon(Normal/Flug). Arbok greift");
		TextWechselZuPassenderKategorie.put("zweiterVersuch", "Da wir uns in diesem Guide eher mit dem Wettkampf-Aspekt des Spieles beschäftigen, lassen wir den Sammel-Aspekt des  Spieles aus. Also was genau macht einen Pokémon-Kampf?Das 0815-Pokemon-KampfFormat, wird als Einzelkampf bezeichnet, in dem sich zwei Pokémon gegenüberstehen. Hierbei ist natürlich zu beachten, dass es sich um 801 verschiedene Wesen handelt.  Im Kampf ist es möglich, aus 4 verschiedenen Pokémon Attacken zu wählen. Desweiterein existiert das Doppelkampf-, Dreierkampf- und Rotationskampfformat. Da dies unser VGC-Project (Video Game Championship) ist, werden wir uns auf den Doppelkampf-Format fokussieren, da nur dieser bei den Championships gespielt wird. (Das wollten WIR, diese Guide wurder jedoch zu einem Pokémon-Basics-Guide umgeformt :'D, also könnt ihr den VGC-Banner getrost ignorieren ;D. ");
		TextWechselZuPassenderKategorie.put("WorausBestehtEinPokémon","Kommen wir nun zu dem Bread&Butter, also dem Kern der Pokémon. Ihre Typen, sowie ihr Wesen, ihre Fähigkeiten, ihre Werte und natürlich ihre Attacken. Insgesamt gibt es 18 Typen, die verschiedene Wechselwirkungen aneinander besitzen. Als Beispiel, wie an dem Bild zu erkennen, ist der Typ Unlicht  anfällig für den Typ Kampf, wobei aber der Typ Kampf kaum Schaden durch den Unlicht-Typen erleidet. Es wird unterschieden zwischen Null-Effektivität, nicht sehr effektiv, effektiv und sehr effektiv. Hierbei ist natürlich zu erwähnen, dass die Pokémon-Attacken ihren eigen Typen besitzen. Darauf kommen wir aber wieder in der Damage Calculation zu sprechen. "); 
		TextWechselZuPassenderKategorie.put("RotomBsp","Desweiteren besitzt jedes Pokémon eine Fähigkeit, die im Kampf zum Einsatz kommt. Als Beispiel habe ich nun das Pokémon Rotom gewählt, welches die Fähigkeit Schwebe besitzt. Diese erlaubt es ihm, von Attacken des Typ Bodens unberührt zu bleiben. Als Kontrast hierzu existiert die Fähigkeit Überbrückung, die andere Fähigkeiten überbrückt. Also könnte das Pokémon Maxax mit der Attacke Erdbeben das Pokémon Rotom treffen, wodurch die Null-Effektivität zur 2x Effektivität wird, da Rotom ein Elektro-Typ Pokémon ist");
		TextWechselZuPassenderKategorie.put("WorausBestehtEinPokémon2", "Die Stats werden wir in einem anderen Segment näher beleuchtet, aber um es erwähnt zu haben, besitzt ein Pokémon Hp-Atk-Def-Spe.Atk-Sp.Def-Init-Werte. Außerdem können diese durch das Wesen eines Pokémon beeinflusst werden. Insgesamt existieren 25 Wesen wie z.B das Wesen Hart, welches den Angriffswert erhöht und den Spezial-Angriffswert verringert. Dabei werden diese Werte um entweder 10% erhöht oder verringert. Es gibt auch versteckte Wert-Modifizierer wie die DVs(IVs auf Englisch) und die EVs. Dvs(Determinant Values) sind versteckte Werte, die ab der 3.Generation von Pokémon einen Minimalwert von 0 und einen Maximalwert von 31 ergeben können. Diese sind unbeinflussbar. Man kann insgesamt 510 Evs auf die Stats verteilen. Zum Beispiel 252(maximum) in HP, 252 in Atk und 4 auf Init. Alle 4 Evs wird der Wert um 1 erhöht. Die Evs erhält man aus Offline-Pokemon-Kämpfen, also aus dem Spiel.");
		TextWechselZuPassenderKategorie.put("DamageCalc","Das, worum es in einem Pokémon-Kampf geht, ist die gegenerischen Kp bzw. Hp auf 0 zu setzen. In diesem Abschnitt erkläre ich dir, wie denn nun der Schaden berechnet wird, den ein Pokémon erleidet. Dies ist von Pokémon zu Pokémon und Attacke zu Attacke unterschiedlich, da sie alle über verschiedene Werte verfügen. Nehmen wir als Beispiel die zwei Pokémon Arbok(Gift) und Tukanon(Normal/Flug). Arbok greift mit der Attacke Säure, die 40 Basisstärke besitzt und Spezial ist(251), das Pokémon Tukanon an, welches(mal angenommen) einen Spezial-Verteidigunswert von 273 besitzt. Beide Pokémon befinden sich auch LVL 100. Diese Werte müssen dann lediglich in die untere Formel eingesetzt werden, wobei Z eine zahl zwischen 85 und 100 ist. F1-F3 sind Variablen, die für uns erstmal egal sind. Der Volltreffer ist 1.5, jedoch kann er auch 1 sein, was heißt, dass kein Volltreffer geglückt ist.STAB ist der SameTypeAttackBonus. 1.5 falls die Attacke, die man einsetzt den selben Typ hat, wie das Pokémon. ");
		TextWechselZuPassenderKategorie.put("DamageCalc2","Mit Typ1 bzw. Typ2 ist gemeint, ob die Attacke nicht sehr effektiv oder sehr effektiv war(0.5 o. 2 o. Falls neutral, dann 1). Setzt man nun die Werte in die Formel ein, kommt man auf ~49 Schaden. Also werden Tukanon 49 HP von seinen 364 abgezogen."); 
				   
	}
}
